### ISSUE TITLE
Adding User Metadata Fields

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/back-end#18]
### Add Metadata in Database Users

Thought I would mention here, simply to have a list of all the requirements in a well structured and easy to find place.

The `User` objects in the database will need to be updated to hold the correct metadata for each created user. The new required fields are the following: 

* `accountType` - Enum of `Admin`, `Regular User`, `Guest`, or `Developer`
* `lastLogin` - Epoch time of the last login of the user
* `createdAt` - Epoch time of the creation of the user
* `dept` - Enum of all department names, e.g `Electronics` 
* `memberType` - Shows the type of member that the user is. Examples could include `Member`, `Committee` or `Tier 1`

The need for the last - `memberType` - is mostly to unlink permissions from account types. For example, someone might need access to Admin privileges without being in the committee. 

This info will be shown in the account page as well as the Admin page, accessible only by Admin users.

**Comment by Nathanrs97** [comment]
The meta field can be updated with any field the front-end wants
